name: merch_store_mobile
description: A mobile version of the merch store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  timeago: ^3.6.0
  firebase_storage: ^11.5.6
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3
  google_sign_in: ^6.2.1
  http: ^1.1.2
  uuid: ^4.5.1
  webview_flutter: ^4.4.2
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.6.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.5
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - public/
    - .env 